# This is a basic workflow to help you get started with Actions

name: Jekyll Source - Master 

on:
  push:
    branches: [ source ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

#/home/runner/work/devjaedol.github.io/devjaedol.github.io
      - name: Run PWD
        run: pwd

      - name: Run ls -al
        run: ls -al

# Commit id => cea156d3c47dbbd70b84fb7518bdecbba36445ad
      - name: Check COMMIT_ID
        env : 
          COMMIT_ID : ${{github.sha}}
        run: echo "Commit id => $COMMIT_ID"

      - name: Check REPO_TOKEN
        env : 
          REPO_TOKEN : ${{secrets.REPO_TOKEN}}
        run: echo "REPO_TOKEN => $REPO_TOKEN"


      - name: Cloning source branch
        uses: actions/checkout@v2
        with:
          ref: 'source'
          path: 'source'

      - name: Building site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}/source:/srv/jekyll -v ${{ github.workspace }}/source/_site:/srv/jekyll/_site \
          veerendrav2/my-jekyll:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Cloning master branch
        uses: actions/checkout@v2
        with:
          ref: 'master'
          path: 'master'

      - name: Run ls -al
        run: ls -al

      - name: Copying _site content to master branch repo
        run: cp -R ${{ github.workspace }}/source/_site/* ${{ github.workspace }}/master
              
